//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaoTaoBem_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbComments
    {
        public int IdComment { get; set; }
        public string Comment { get; set; }
        public int RecipeId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public byte StatusID { get; set; }
    
        public virtual tbRecipes tbRecipes { get; set; }
        public virtual tbStatus tbStatus { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
