//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaoTaoBem_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIngredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbIngredients()
        {
            this.tbRecipeIngredient = new HashSet<tbRecipeIngredient>();
        }
    
        public int IdIngredient { get; set; }
        public string IngredientName { get; set; }
        public byte IngCategoryId { get; set; }
    
        public virtual tbIngredientCategory tbIngredientCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRecipeIngredient> tbRecipeIngredient { get; set; }
    }
}
