//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaoTaoBem_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRecipeIngredient
    {
        public int IdRecipe { get; set; }
        public int IdIngredient { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public byte UnitId { get; set; }
    
        public virtual tbIngredients tbIngredients { get; set; }
        public virtual tbRecipes tbRecipes { get; set; }
        public virtual tbUnits tbUnits { get; set; }
    }
}
