//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaoTaoBem_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUnits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUnits()
        {
            this.tbRecipeIngredient = new HashSet<tbRecipeIngredient>();
        }
    
        public byte IdUnit { get; set; }
        public string UnitName { get; set; }
        public byte UnitCategoryId { get; set; }
        public byte UnitSystemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRecipeIngredient> tbRecipeIngredient { get; set; }
        public virtual tbUnitCategory tbUnitCategory { get; set; }
        public virtual tbUnitSystem tbUnitSystem { get; set; }
    }
}
